interface ExpoPluginConfig {
  extensionSettings: Record<string, any>;
  buildConfig: BuildConfig;
  helpers: ConfigHelpers;
}

interface ConfigHelpers {
  getPackageName: () => string;
  getPlatform: () => 'ios' | 'android';
  getExtensionSetting: (extensionName: string, key: string) => any;
  getAppConfig: () => any;
  getBuildOption: (key: string) => any;
}

interface BuildConfig {
  app?: {
    data?: {
      packagename?: string;
      extensions?: Record<string, any>;
    };
  };
  template?: {
    platform?: string;
  };
  build_options?: Record<string, any>;
}

/**
 * MoEngage Expo Plugin Configuration
 * 
 * This configuration provides the plugin settings for react-native-expo-moengage.
 * All MoEngage settings (app ID, data center, logs) are read from the config files
 * generated by app.plugin.js, which uses the official MoEngage config key format.
 * 
 * Dashboard Settings (used by app.plugin.js to generate config files):
 * - moengage_app_id: MoEngage workspace ID (e.g., "KPJ4U8FK5F762R9R8817H6V1")
 * - moengage_data_center: Data center integer (1=US, 2=EU, 3=India, 4=SERV1, 5=SERV2, 6=SERV3)
 * - moengage_ios_debug: Enable debug logs on iOS (also used for Android for consistency)
 * 
 * For more information:
 * https://developers.moengage.com/hc/en-us/articles/39610614807828-Configure-the-MoEngage-Expo-SDK
 */
export default function getMoEngageExpoPlugin(config: ExpoPluginConfig): [string, any] {
  // The react-native-expo-moengage plugin only uses file-based configuration
  // All MoEngage settings (app ID, data center, logs) are read from the XML/plist files
  // generated by app.plugin.js

  // Build the MoEngage plugin configuration
  // Note: Config files are generated by app.plugin.js with correct official keys
  const pluginConfig = {
    android: {
      configFilePath: 'assets/moengage/android_initilisation_config.xml',
      smallIconPath: 'assets/moengage/small_icon.png',
      largeIconPath: 'assets/moengage/large_icon.png',
      disableMoEngageDefaultBackupFile: false,
      includeFirebaseMessagingDependencies: true,
      isExpoNotificationIntegration: true,
      shouldIncludeMoEngageFirebaseMessagingService: true,
    },
    apple: {
      configFilePath: 'assets/moengage/MoEngage-Config.plist',
      pushNotificationImpressionTrackingEnabled: true,
      richPushNotificationEnabled: true,
      pushTemplatesEnabled: true,
      deviceTriggerEnabled: true,
    }
  };

  return [
    'react-native-expo-moengage',
    pluginConfig
  ];
}
